### ISSUE TITLE
HTTPX error

### ISSUE THREAD

**Issue by IgnacioHeredia** [pederhan/harborapi#102]
Latest version of `httpx` is breaking `harborapi`:
```
>>> import harborapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/harborapi/__init__.py", line 5, in <module>
    from . import client
  File "/usr/local/lib/python3.10/dist-packages/harborapi/client.py", line 25, in <module>
    from httpx._types import VerifyTypes
ImportError: cannot import name 'VerifyTypes' from 'httpx._types' (/usr/local/lib/python3.10/dist-packages/httpx/_types.py)
```
[Suggested temporal patch](https://github.com/langchain-ai/langserve/issues/796) is working: 
`pip install httpx==0.27.2`

**Comment by lennardk** [comment]
This will probably need a similar change as mentioned in https://github.com/encode/httpx/issues/3443#issuecomment-2515310246.

**Comment by jonkerj** [comment]
I'm running into this exact issue. Harborapi requires `httpx>=0.22.0` and `VerifyTypes` has been removed in `encode/httpx` per httpx 0.28.0. So either httpx needs to be pinned (<0.28.0), or harborapi needs to do without `VerifyTypes`

**Comment by jonkerj** [comment]
Workaround:

```
$ pip install 'httpx>=0.22.0,<0.28.0'
```

**Comment by pederhan** [comment]
This is fixed in #103.

```
pip install harborapi==0.26.2
```

**Comment by pederhan** [comment]
Fixed in 0.26.2:

```
pip install harborapi==0.26.2
```
