### ISSUE TITLE
Error with latest Pydantic

### ISSUE THREAD

**Issue by IgnacioHeredia** [pederhan/harborapi#95]
Pydantic 2.10.1 seems to break Harborapi.
```console
>>> from harborapi import HarborClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/harborapi/__init__.py", line 4, in <module>
    from . import auth
  File "/usr/local/lib/python3.10/dist-packages/harborapi/auth.py", line 10, in <module>
    from harborapi.models.models import Robot
  File "/usr/local/lib/python3.10/dist-packages/harborapi/models/__init__.py", line 3, in <module>
    from . import scanner
  File "/usr/local/lib/python3.10/dist-packages/harborapi/models/scanner.py", line 55, in <module>
    class ScannerProperties(StrDictRootModel[str]):
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 811, in __class_getitem__
    submodel = _generics.create_generic_submodel(model_name, origin, args, params)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_generics.py", line 137, in create_generic_submodel
    created_model = meta(
  File "/usr/local/lib/python3.10/dist-packages/pydantic/_internal/_model_construction.py", line 137, in __new__
    cls = cast('type[BaseModel]', super().__new__(mcs, cls_name, bases, namespace, **kwargs))
  File "/usr/lib/python3.10/abc.py", line 106, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: mro() returned a non-class ('PydanticRecursiveRef')
```
Pydantic 2.9.2 works though!
```console
>>> from harborapi import HarborClient
>>> 
```

**Comment by pederhan** [comment]
I'll look into it ASAP.
